// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 C:/Program Files/Git/saint_teresa_of_avila.glb 
Author: Igor Harmendani (https://sketchfab.com/igorharmendani)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/saint-teresa-of-avila-3415438a5e904579aff98d4ab2c2ffca
Title: Saint Teresa of Avila
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import {
  ExtendedColors,
  Overwrite,
  NodeProps,
  NonFunctionKeys,
  Vector3,
  Euler,
  Matrix4,
  Quaternion,
  Layers,
} from '@react-three/fiber'
import { EventHandlers } from '@react-three/fiber/dist/declarations/src/core/events'
import { Group, Object3DEventMap } from 'three'

export function SaintTeresa(
  props: React.JSX.IntrinsicAttributes &
    Omit<
      ExtendedColors<
        Overwrite<
          Partial<Group<Object3DEventMap>>,
          NodeProps<Group<Object3DEventMap>, Group>
        >
      >,
      NonFunctionKeys<{
        position?: Vector3
        up?: Vector3
        scale?: Vector3
        rotation?: Euler
        matrix?: Matrix4
        quaternion?: Quaternion
        layers?: Layers
        dispose?: (() => void) | null
      }>
    > & {
      position?: Vector3
      up?: Vector3
      scale?: Vector3
      rotation?: Euler
      matrix?: Matrix4
      quaternion?: Quaternion
      layers?: Layers
      dispose?: (() => void) | null
    } & EventHandlers
) {
  const { nodes, materials } = useGLTF('/saint_teresa_of_avila.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.clip} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.eyes} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.head} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.teeth} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.toque} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.tunic} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.veil} />
      </group>
    </group>
  )
}

useGLTF.preload('/saint_teresa_of_avila.glb')
